---
# Source: kc-ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "kc-ui-service"
  labels:
    chart: "kc-ui-1.0.0"
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3010
    nodePort: 31010
  selector:
    app: kc-ui
    release: RELEASE-NAME
